// mod print;
// mod vars;
// mod types;
// mod typles;
// mod string_example;
// mod array_value;
// mod FIndLArgestNumber;
mod GenericTypes;
// mod vector_array;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs_ref;
// mod enums_ref;
// mod cli;
// mod guess_game;
// mod structs_ref2;
// mod enumsV2;
// mod pattern;
fn main(){
    // print::run();
    // vars::vars();
    // types::run();
    // string_example::run();
    // typles::run();
    // array_value::run();
    // vector_array::run();
    // conditionals::run();
    // loops::run();
    // functions::run();
    // pointer_ref::run();
    // structs_ref::run();
    // enums_ref::run();
    // cli::run();
    // guess_game::run();
    // structs_ref2::run();
    // enumsV2::run();
    // pattern::run();
    // FIndLArgestNumber::run();
    GenericTypes::run();
}