// mod print;
// mod vars;
// mod types;
// mod typles;
// mod string_example;
// mod array_value;
// mod vector_array;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs_ref;
mod enums_ref;
mod cli;
fn main(){
    // print::run();
    // vars::vars();
    // types::run();
    // string_example::run();
    // typles::run();
    // array_value::run();
    // vector_array::run();
    // conditionals::run();
    // loops::run();
    // functions::run();
    // pointer_ref::run();
    // structs_ref::run();
    enums_ref::run();
    cli::run();
}